#+title: @bevsxyz's Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ~/.config/emacs/init.el :mkdirp yes

I had started my Emacs journey with the [[https://www.youtube.com/playlist?list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ][Emacs From Scratch]] series by [[https://github.com/daviwil][@daviwil]]. I had used his configuration and built my own Emacs
configuration largely copying from his [[https://github.com/daviwil/emacs-from-scratch][EFS repo]]. Well now I think I have graduated having done my exploration of Emacs, and would like
to write my very own configuration, customised to my liking.  And that's what I am gonna do. Satisfying my inner control freak!!! Yaay!!!

* Initialize My Configuration

Let us begin by setting some variables that we will be using further in the configuration. Perhaps I will use this block religiously to declare all
of the variables to configure my setup or not depending on how much I crave for clean code. Let us hope I stick to my code cleaning monthly at the very least.

#+begin_src emacs-lisp
  ;; NOTE: init.el is now generated from Emacs.org.  Please edit that file
  ;;       in Emacs and init.el will be generated automatically!

  (defvar bevsxyz/default-font-size 200)
  (defvar bevsxyz/default-variable-font-size 200)
  (defvar bevsxyz/frame-transparency '(90 . 90))

#+end_src

** Startup Performance

#+begin_src emacs-lisp

  ;; The default is 800 kilobytes.  Measured in bytes.
  (setq gc-cons-threshold (* 50 1000 1000))

  (defun bevsxyz/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                      (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'bevsxyz/display-startup-time)

#+end_src

** Package Manager for Emacs!!

I have used [[https://github.com/jwiegley/use-package][use-package]] for a while now and loved it. It is neat and tidy. I came across [[https://github.com/radian-software/straight.el][Straight.el]] recently and oh boy does it live upto it's
description. And what's more I can retain my previous use-package declarations without much change and make it use straight underneath instead of the default package.el. I am impressed!

First, let us get into bootstrapping the straight package manger for our emacs.

#+begin_src emacs-lisp

  (setq package-enable-at-startup nil)
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

#+end_src

Since I am gonna use `use-package`, we will have to install it with `straight.el` and initialize it.

#+begin_src emacs-lisp

  (straight-use-package 'use-package
                        :custom (setq straight-use-package-by-default t))

#+end_src

** Automatic Package Updates

The [[https://github.com/rranelli/auto-package-update.el][auto-package-update]] package helps to keep our Emacs package up to date independent of straight.el. I am not happy with the start-up
times of straight.el. This had worked with use-package alone previously and ought to work. Let us say this is still a testing issue.

You can also use =M-x auto-package-update-now= to update right now!

#+begin_src emacs-lisp

  (setq straight-check-for-modifications nil)

  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))

#+end_src

**  Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp

  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
                                          ;(setq user-emacs-directory "~/.cache/emacs")

  (use-package no-littering
    ;; no-littering doesn't set this by default so we must place
    ;; auto save files in the same path as it uses for sessions
    :custom (auto-save-file-name-transforms
             `((".*" ,(no-littering-expand-var-file-name "auto-save/") t))))

#+end_src

** Basic User Interface

We will configure the minimal UI setting retaining stuff I want and removing other bloats. Un-comment the =(menu-bar-mode -1)= if you fancy removing the menu bar.

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

                                          ;(menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell nil)

  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; Set frame transparency
  (set-frame-parameter (selected-frame) 'alpha bevsxyz/frame-transparency)
  (add-to-list 'default-frame-alist `(alpha . ,bevsxyz/frame-transparency))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  treemacs-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

*** Font Configuration

I am using the [[https://github.com/tonsky/FiraCode][Fira Code]] and [[https://fonts.google.com/specimen/Cantarell][Cantarell]] fonts for this configuration which will more than likely need to be installed on your machine.  Both can usually be found in the various Linux distro package managers or downloaded from the links above.

#+begin_src emacs-lisp

    (set-face-attribute 'default nil
                        :font "Fira Code Retina"
                        :height bevsxyz/default-font-size)

    ;; Set the fixed pitch face
    (set-face-attribute 'fixed-pitch nil
                        :font "Fira Code Retina"
                        :height bevsxyz/default-font-size)

    ;; Set the variable pitch face
    (set-face-attribute 'variable-pitch nil
                        :font "Cantarell"
                        :height bevsxyz/default-variable-font-size
                        :weight 'regular)

#+end_src

** Extended User Interface

*** Color Theme

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety and support for many different Emacs modes.  Taking a look at the [[https://github.com/hlissner/emacs-doom-themes/tree/screenshots][screenshots]] might help you decide which one you like best.  You can also run =M-x counsel-load-theme= to choose between them easily.

#+begin_src emacs-lisp

  (use-package doom-themes
    :config (load-theme 'doom-city-lights t))

#+end_src

*** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

  (use-package all-the-icons)

  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 15)))

#+end_src

*** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))

#+end_src

* Key Board Short Cuts

** Set-up Packages

*** General.el

[[https://github.com/noctuid/general.el][General.el]] is used for easy keybinding configuration that integrates well with which-key.

#+begin_src emacs-lisp

  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  (use-package general
    :after evil
    :config
    (general-create-definer bevsxyz/leader-keys
      :keymaps '(normal insert visual emacs)
      :prefix "SPC"
      :global-prefix "C-SPC")

    (bevsxyz/leader-keys
      "t"  '(:ignore t :which-key "toggles")
      "tt" '(counsel-load-theme :which-key "choose theme")
      "fde" '(lambda () (interactive)
               (find-file (expand-file-name "~/.local/share/chezmoi/dot_config/emacs/Emacs.org")))))

#+end_src

*** Evil-mode

[[https://evil.readthedocs.io/en/latest/index.html][Evil-mode]] for a Vi-like modal editing experience.

#+begin_src emacs-lisp

  (use-package evil
    :custom
    (evil-want-integration t)
    (evil-want-keybinding nil)
    (evil-want-C-u-scroll t)
    (evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

#+end_src

*** Evil-collection

[[https://github.com/emacs-evil/evil-collection][Evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

#+begin_src emacs-lisp

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))

#+end_src




* Life of Writing/Development

* Organizing with Org

[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

** Configuration

Well all of the org configurations
*** Basic
The =bevsxyz/org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly.

#+begin_src emacs-lisp

  (defun bevsxyz/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil
                          :font "Cantarell"
                          :weight 'regular
                          :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil
                        :foreground nil
                        :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil
                        :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil
                        :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil
                        :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil
                        :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil
                        :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil
                        :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil
                        :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil
                        :inherit 'fixed-pitch)
    (set-face-attribute 'line-number t
                        :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil
                        :inherit 'fixed-pitch))

#+end_src

This section contains the basic configuration for =org-mode= plus the configuration for Org agendas and capture templates.  There's a lot to unpack in here so I'd recommend watching the videos for [[https://youtu.be/VcgjTEa0kU4][Part 5]] and [[https://youtu.be/PNE-mgkZ6HM][Part 6]] for a full explanation.

#+begin_src emacs-lisp

  (defun bevsxyz/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  (use-package org
    :hook (org-mode . bevsxyz/org-mode-setup)
    :custom
    (org-ellipsis " ▾")
    :config
    (bevsxyz/org-font-setup))

#+end_src

*** Extended UI Settings
**** Nicer Heading Bullets

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.

#+begin_src emacs-lisp

  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

**** Center Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document.  This is really a matter of personal preference so you can remove the block below if you don't like the behavior.

#+begin_src emacs-lisp

  (defun bevsxyz/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . bevsxyz/org-mode-visual-fill))

#+end_src

*** Code Blocks
**** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (python . t)))

    (push '("conf-unix" . conf-unix) org-src-lang-modes))

#+end_src

**** Structure Templates

Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    ;; This is needed as of Org 9.2
    (require 'org-tempo)

    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("py" . "src python")))

#+end_src

**** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =bevsxyz/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun bevsxyz/org-babel-tangle-config ()
    (when (string-equal (file-name-directory (buffer-file-name))
                        (concat "/home/" user-real-login-name "/.local/share/chezmoi/dot_config/emacs/"))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'bevsxyz/org-babel-tangle-config)))

#+end_src

** My Second Brain

[[https://github.com/org-roam/org-roam][Org-roam]] is a org extension to create and manage a second brain. I need to use it to extend my memory!

*** Configuration
#+begin_src emacs-lisp
  (use-package org-roam
    :custom
    (org-roam-directory "~/projects/org-roam")
    (org-roam-completion-everywhere t)
    (org-roam-dailies-directory "journal/")
    (org-roam-dailies-capture-templates
     '(("d" "default" entry "* %<%I:%M %p>: %?"
        :if-new (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n\nMood: %^{Mood}\n\n")
        )))
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
        :unnarrowed t))
     '(("p" "project" plain (file "~/projects/org-roam/templates/ProjectNoteTemplate.org")
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: Project")
        :unnarrowed t)))
    :bind (("C-c n l" . org-roam-buffer-toggle)
           ("C-c n f" . org-roam-node-find)
           ("C-c n i" . org-roam-node-insert)
           :map org-mode-map
           ("C-M-i" . completion-at-point)
           :map org-roam-dailies-map
           ("Y" . org-roam-dailies-capture-yesterday)
           ("T" . org-roam-dailies-capture-tomorrow))
    :bind-keymap
    ("C-c n d" . org-roam-dailies-map)
    :config
    (require 'org-roam-dailies) ;; Ensure the keymap is available
    (org-roam-db-autosync-mode)
    )
#+end_src

*** Custom Functions

Some custom function I have stolen from [[https://systemcrafters.net/build-a-second-brain-in-emacs/5-org-roam-hacks/][systemcrafters]].

**** Org Agenda

List roam project files with TODO in the org-agenda list of files.

#+begin_src emacs-lisp

  (require 'org-roam)
  (defun org-roam-node-insert-immediate (arg &rest args)
    (interactive "P")
    (let ((args (push arg args))
          (org-roam-capture-templates (list (append (car org-roam-capture-templates)
                                                    '(:immediate-finish t)))))
      (apply #'org-roam-node-insert args)))


  (defun bevsxyz/org-roam-list-notes-by-tag (tag-name)
    (mapcar #'org-roam-node-file
            (seq-filter
             (lambda (node) (string-equal (nth 0 (org-roam-node-tags node)) tag-name))
             (org-roam-node-list))))
  (defun bevsxyz/org-roam-refresh-agenda-list ()
    (interactive)
    (setq org-agenda-files (bevsxyz/org-roam-list-notes-by-tag "Project")))

  ;; Build the agenda list the first time for the session
  (bevsxyz/org-roam-refresh-agenda-list)

#+end_src

**** Custom Project Find Function

#+begin_src emacs-lisp
  (defun bevsxyz/org-roam-project-finalize-hook ()
    "Adds the captured project file to `org-agenda-files' if the
  capture was not aborted."
    ;; Remove the hook since it was added temporarily
    (remove-hook 'org-capture-after-finalize-hook #'bevsxyz/org-roam-project-finalize-hook)

    ;; Add project file to the agenda list if the capture was confirmed
    (unless org-note-abort
      (with-current-buffer (org-capture-get :buffer)
        (add-to-list 'org-agenda-files (buffer-file-name)))))

  (defun bevsxyz/org-roam-find-project ()
    (interactive)
    ;; Add the project file to the agenda after capture is finished
    (add-hook 'org-capture-after-finalize-hook #'bevsxyz/org-roam-project-finalize-hook)

    ;; Select a project file to open, creating it if necessary
    (org-roam-node-find
     nil
     nil
     (bevsxyz/org-roam-filter-by-tag "Project")
     :templates
     '(("p" "project" plain  (file "~/projects/org-roam/templates/ProjectNoteTemplate.org")
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+category: ${title}\n#+filetags: Project")
        :unnarrowed t))))

  (global-set-key (kbd "C-c n p") #'bevsxyz/org-roam-find-project)
#+end_src

**** Inbox

Capture notes in a single org file for all the spontaneous ideas which later can be refiled.

#+begin_src emacs-lisp
  (defun bevsxyz/org-roam-capture-inbox ()
    (interactive)
    (org-roam-capture- :node (org-roam-node-create)
                       :templates '(("i" "inbox" plain "* %?"
                                    :if-new (file+head "Inbox.org" "#+title: Inbox\n")))))

  (global-set-key (kbd "C-c n b") #'bevsxyz/org-roam-capture-inbox)
#+end_src

**** Capture Tasks to Project

#+begin_src emacs-lisp
  (defun bevsxyz/org-roam-capture-task ()
    (interactive)
    ;; Add the project file to the agenda after capture is finished
    (add-hook 'org-capture-after-finalize-hook #'bevsxyz/org-roam-project-finalize-hook)

    ;; Capture the new task, creating the project file if necessary
    (org-roam-capture- :node (org-roam-node-read
                              nil
                              (bevsxyz/org-roam-filter-by-tag "Project"))
                       :templates '(("p" "project" plain "** TODO %?"
                                     :if-new (file+head+olp "%<%Y%m%d%H%M%S>-${slug}.org"
                                                            "#+title: ${title}\n#+category: ${title}\n#+filetags: Project"
                                                            ("Tasks"))))))
#+end_src

**** Automatically copy (or move) completed tasks to dailies

#+begin_src emacs-lisp
  (defun bevsxyz/org-roam-copy-todo-to-today ()
    (interactive)
    (let ((org-refile-keep t) ;; Set this to nil to delete the original!
          (org-roam-dailies-capture-templates
           '(("t" "tasks" entry "%?"
              :if-new (file+head+olp "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n" ("Tasks")))))
          (org-after-refile-insert-hook #'save-buffer)
          today-file
          pos)
      (save-window-excursion
        (org-roam-dailies--capture (current-time) t)
        (setq today-file (buffer-file-name))
        (setq pos (point)))

      ;; Only refile if the target file is different than the current file
      (unless (equal (file-truename today-file)
                     (file-truename (buffer-file-name)))
        (org-refile nil nil (list "Tasks" today-file nil pos)))))

  (add-to-list 'org-after-todo-state-change-hook
               (lambda ()
                 (when (equal org-state "DONE")
                   (bevsxyz/org-roam-copy-todo-to-today))))
#+end_src

* Applications

Some special use applications inside emacs are configured here.

** EAF

[[https://github.com/emacs-eaf/emacs-application-framework][Emacs Application Framework]] extends the graphical capabilities of emacs utilising Qt6. It has a number of applications, but we will only use the browser and the pdf reader.

#+begin_src emacs-lisp

  (use-package eaf
    :straight (eaf
               :type git
               :host github
               :repo "emacs-eaf/emacs-application-framework"           
               :files ("*.el" "*.py" "core" "app" "*.json")
               :includes (eaf-pdf-viewer eaf-browser)
               :pre-build (("./install-eaf.py" "--install" "pdf-viewer browser" "--ignore-sys-deps"))
               ))
  (evil-set-initial-state 'eaf-mode 'emacs)

#+end_src

*** Browser

#+begin_src emacs-lisp

  (use-package eaf-browser)

#+end_src

*** PDF Viewer

#+begin_src emacs-lisp

  (use-package eaf-pdf-viewer)

#+end_src

